# Generated by Django 3.0.10 on 2020-12-10 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Dirección')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripcion')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Banner')),
                ('profile_image', models.ImageField(blank=True, help_text='Recomendamos que la imagen sea de relacion de aspecto 1:1', null=True, upload_to='', verbose_name='Foto de perfil')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'db_table': 'bussiness',
            },
        ),
        migrations.CreateModel(
            name='UserBusiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('AD', 'Administrador')], max_length=2)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='business.Business')),
            ],
        ),
    ]
