# Generated by Django 3.0.10 on 2020-10-01 06:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='members',
        ),
        migrations.AddField(
            model_name='business',
            name='user',
            field=models.ManyToManyField(related_name='business', through='business.UserBusiness', to=settings.AUTH_USER_MODEL),
        ),
    ]
