# Generated by Django 3.0.10 on 2020-12-10 04:27

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbusiness',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='business',
            name='user',
            field=models.ManyToManyField(related_name='business', through='business.UserBusiness', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='business',
            index=django.contrib.postgres.indexes.HashIndex(fields=['slug'], name='bussiness_slug_4ab3b3_hash'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['name'], name='bussiness_name_845a7b_btree'),
        ),
    ]
