# Generated by Django 3.0.10 on 2020-12-09 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20201001_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='business',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Banner'),
        ),
        migrations.AlterField(
            model_name='business',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='business',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Recomendamos que la imagen sea de relacion de aspecto 1:1', null=True, upload_to='', verbose_name='Foto de perfil'),
        ),
        migrations.AlterField(
            model_name='userbusiness',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='business.Business'),
        ),
    ]
