# Generated by Django 3.0.10 on 2020-12-10 02:26

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_auto_20201209_0551'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='business',
            index=django.contrib.postgres.indexes.HashIndex(fields=['slug'], name='bussiness_slug_4ab3b3_hash'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['name'], name='bussiness_name_845a7b_btree'),
        ),
    ]
