# Generated by Django 3.0.10 on 2020-12-10 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='posts.Post'),
        ),
    ]
