# Generated by Django 3.0.10 on 2020-10-16 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_auto_20201010_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='send_date',
            field=models.DateField(null=True),
        ),
    ]
