# Generated by Django 3.0.10 on 2020-12-10 04:27

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0002_auto_20201210_0427'),
        ('chat_app', '0002_deal_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Business'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='chat_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_app.ChatRoom'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=django.contrib.postgres.indexes.HashIndex(fields=['slug'], name='chat_app_ch_slug_a0a3ed_hash'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['send_date'], name='chat_app_ch_send_da_a3aeea_btree'),
        ),
    ]
