# Generated by Django 3.0.10 on 2020-10-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0003_chatmessage_send_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='user_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
