# Generated by Django 3.0.10 on 2020-10-20 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0004_chatmessage_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='user_name',
            new_name='sender_name',
        ),
    ]
