# Generated by Django 3.0.10 on 2020-10-28 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20201001_0003'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat_app', '0005_auto_20201020_0510'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total', models.FloatField()),
                ('delivery', models.IntegerField(choices=[(1, 'Entrega a domicilio'), (2, 'Pick-up'), (3, 'Punto de encuentro')], default=1)),
                ('approved', models.BooleanField(default=False)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='business.Business')),
                ('chat_message', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='chat_app.ChatMessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
