# Generated by Django 3.0.10 on 2020-11-09 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0009_chatmessage_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='send_verifier',
            field=models.UUIDField(unique=True),
        ),
    ]
