# Generated by Django 3.0.10 on 2020-12-10 02:26

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0010_auto_20201109_0026'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chatmessage',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['send_date'], name='chat_app_ch_send_da_a3aeea_btree'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=django.contrib.postgres.indexes.HashIndex(fields=['slug'], name='chat_app_ch_slug_a0a3ed_hash'),
        ),
    ]
