# Generated by Django 3.0.10 on 2020-10-01 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='categories', verbose_name='Banner')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(null=True)),
                ('modified_at', models.DateTimeField(null=True)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField()),
                ('discount', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('AC', 'Active'), ('IN', 'Inactive')], default='AC', max_length=2)),
                ('classification', models.CharField(choices=[('AR', 'Article'), ('SR', 'Service')], default='AR', max_length=2)),
                ('upvotes', models.IntegerField(default=0)),
                ('last_confirmation', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Business')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Category')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts')),
                ('alternative_text', models.CharField(max_length=100)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='posts.Post')),
            ],
        ),
    ]
