# Generated by Django 3.0.10 on 2020-12-10 04:27

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import laya_shop.posts.models
import laya_shop.posts.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=40)),
                ('type', models.CharField(choices=[('STRING', 'String'), ('MEASURE', 'Measure'), ('DIMENSION', 'Dimension'), ('LIST', 'List'), ('COLOR', 'Color')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalAttributeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalAttributesValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='BusinessImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=laya_shop.posts.utils.business_directory_files)),
                ('is_valid', models.BooleanField(default=False)),
                ('alternative', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessImageThumbnails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumb_200x200', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='categories', verbose_name='Banner')),
                ('slug', models.SlugField(blank=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=10)),
                ('rate', models.FloatField()),
                ('iso_code', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(null=True)),
                ('modified_at', models.DateTimeField(null=True)),
                ('title', models.CharField(max_length=50)),
                ('title_slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('attributes', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('base_price', models.FloatField(blank=True)),
                ('discount', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('highlighted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('AC', 'Active'), ('IN', 'Inactive')], default='AC', max_length=2)),
                ('score', models.IntegerField(default=laya_shop.posts.models.random_score)),
                ('state', models.IntegerField(choices=[(1, 'Nuevo'), (2, 'Usado'), (3, 'Por pedido')], default=1)),
                ('delivery', models.IntegerField(choices=[(1, 'Entrega a domicilio'), (2, 'Pick-up'), (3, 'Punto de encuentro')], default=1)),
                ('classification', models.CharField(choices=[('AR', 'Article'), ('SR', 'Service')], default='AR', max_length=2)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None)),
                ('promo', models.CharField(blank=True, max_length=150, null=True)),
                ('upvotes', models.IntegerField(default=0)),
                ('last_confirmation', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='subcategories', verbose_name='Banner')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='posts.Category')),
            ],
            options={
                'verbose_name': 'Subcategory',
                'verbose_name_plural': 'Subcategories',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorias', models.CharField(choices=[('PRODUCTO_ILEGAL', 'Productos Ilegales'), ('ESTAFA', 'Estafa'), ('PUBLICIDAD_ENGANOSA', 'Publicidad Enganosa'), ('ROBO_INTELECTUAL', 'Roba mi propiedad intelectual'), ('CONTRA_TOS', 'Esta en Contra de los TOS')], max_length=255)),
                ('descripcion', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='posts.Post')),
            ],
        ),
    ]
