# Generated by Django 3.0.10 on 2020-09-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='categories', verbose_name='Banner')),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
    ]
