# Generated by Django 3.0.10 on 2020-10-03 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
