# Generated by Django 3.0.10 on 2020-09-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200929_0156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='url',
        ),
        migrations.AddField(
            model_name='postimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts'),
        ),
    ]
