# Generated by Django 3.0.10 on 2020-10-05 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
