# Generated by Django 3.0.10 on 2020-10-06 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20201005_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='subcategories',
        ),
        migrations.AddField(
            model_name='post',
            name='subcategories',
            field=models.ManyToManyField(to='posts.SubCategory'),
        ),
    ]
