# Generated by Django 3.0.10 on 2020-10-06 06:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20201005_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='promo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='discount',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='post',
            name='subcategories',
            field=models.ManyToManyField(related_name='posts', to='posts.SubCategory'),
        ),
    ]
