# Generated by Django 3.0.10 on 2020-10-09 06:25

from django.db import migrations, models
import django.db.models.deletion
import posts.utils


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20201001_0003'),
        ('posts', '0008_auto_20201006_0059'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=posts.utils.business_directory_files)),
                ('is_valid', models.BooleanField(default=False)),
                ('alternative', models.CharField(blank=True, max_length=200, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Business')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='posts.Post')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessImageThumbnails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumb_200x200', models.ImageField(upload_to='')),
                ('business_image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thumbs', to='posts.BusinessImage')),
            ],
        ),
    ]
