# Generated by Django 3.0.10 on 2020-10-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_post_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='state',
            field=models.IntegerField(choices=[(1, 'Nuevo'), (2, 'Usado'), (3, 'Por pedido')], default=1),
        ),
    ]
