# Generated by Django 3.0.10 on 2020-10-11 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_post_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=10)),
                ('rate', models.FloatField()),
                ('iso_code', models.CharField(max_length=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='currency',
        ),
    ]
