# Generated by Django 3.0.10 on 2020-10-11 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20201011_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.Currency'),
        ),
    ]
