# Generated by Django 3.0.10 on 2020-10-11 23:16

from django.db import migrations, models
import laya_shop.posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20201011_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='score',
            field=models.IntegerField(default=laya_shop.posts.models.random_score),
        ),
    ]
