# Generated by Django 3.0.10 on 2020-10-11 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_post_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalattributesvalue',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='additional_attributes', to='posts.Post'),
        ),
    ]
