# Generated by Django 3.0.10 on 2020-10-11 23:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_auto_20201011_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessimage',
            name='attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
