# Generated by Django 3.0.10 on 2020-10-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='base_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
