# Generated by Django 3.0.10 on 2020-11-28 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_post_highlighted'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
