# Generated by Django 3.0.10 on 2020-12-10 02:26

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0026_report'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='currency',
            index=django.contrib.postgres.indexes.HashIndex(fields=['iso_code'], name='posts_curre_iso_cod_5f819b_hash'),
        ),
        migrations.AddIndex(
            model_name='locations',
            index=django.contrib.postgres.indexes.HashIndex(fields=['name'], name='posts_locat_name_3fc01d_hash'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=django.contrib.postgres.indexes.HashIndex(fields=['title'], name='posts_post_title_9fc17e_hash'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=django.contrib.postgres.indexes.HashIndex(fields=['title', 'state'], name='posts_post_title_14d083_hash'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=django.contrib.postgres.indexes.HashIndex(fields=['title', 'state', 'delivery'], name='posts_post_title_3a2d46_hash'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=django.contrib.postgres.indexes.HashIndex(fields=['state'], name='posts_post_state_455cb2_hash'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=django.contrib.postgres.indexes.HashIndex(fields=['delivery'], name='posts_post_deliver_db33a8_hash'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=django.contrib.postgres.indexes.HashIndex(fields=['title_slug'], name='posts_post_title_s_b58cc1_hash'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=django.contrib.postgres.indexes.HashIndex(fields=['highlighted'], name='posts_post_highlig_38a86b_hash'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=django.contrib.postgres.indexes.GinIndex(fields=['tags'], name='posts_post_tags_13448a_gin'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['base_price'], name='posts_post_base_pr_fefcf5_btree'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['created_at'], name='posts_post_created_e63c5c_btree'),
        ),
    ]
