# Generated by Django 3.0.10 on 2020-12-10 04:10

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0027_auto_20201210_0226'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='post',
            name='posts_post_title_14d083_hash',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='posts_post_title_3a2d46_hash',
        ),
        migrations.AddIndex(
            model_name='post',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['title', 'state'], name='posts_post_title_baee49_btree'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['title', 'state', 'delivery'], name='posts_post_title_a71ac7_btree'),
        ),
    ]
