# Generated by Django 3.0.10 on 2020-10-02 14:56

from django.db import migrations, models
import django.db.models.deletion
import laya_shop.filez.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0002_auto_20201001_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=laya_shop.filez.utils.business_directory_files)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Business')),
            ],
        ),
    ]
