# Generated by Django 3.0.10 on 2020-10-03 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20201001_0003'),
        ('filez', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BusinessImage',
            new_name='BusinessTemporalImage',
        ),
    ]
