# Generated by Django 3.0.10 on 2020-10-05 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_subcategory'),
        ('filez', '0004_businessimage_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessimage',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='posts.Post'),
        ),
    ]
