# Generated by Django 3.0.10 on 2020-10-07 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filez', '0005_auto_20201005_0256'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessImageThumbnails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumb_200x200', models.ImageField(upload_to='')),
                ('business_image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thumbs', to='filez.BusinessImage')),
            ],
        ),
    ]
