# Generated by Django 3.0.10 on 2020-12-10 04:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', django.contrib.postgres.fields.jsonb.JSONField()),
                ('sent_by', models.IntegerField(choices=[(1, 'Usuario'), (2, 'BUSINESS')], default=2)),
                ('status', models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Rechazado'), (3, 'Cancelado'), (4, 'Reservado'), (5, 'Acordado'), (6, 'En Delivery'), (7, 'Entregado'), (8, 'Devuelto'), (9, 'Cerrado')], default=1)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='business.Business')),
            ],
        ),
    ]
