# Generated by Django 3.0.10 on 2020-11-21 06:33

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0002_auto_20201001_0003'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', django.contrib.postgres.fields.jsonb.JSONField()),
                ('status', models.IntegerField(choices=[(1, 'Pendiente'), (2, 'rechazado'), (3, 'Cancelado'), (4, 'Reservado'), (5, 'Acordado'), (6, 'Delivery'), (7, 'Entregado'), (8, 'Devuelto')], default=1)),
                ('created_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='business.Business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
