# Generated by Django 3.0.10 on 2020-11-21 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
