# Generated by Django 3.0.10 on 2020-12-10 04:27

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=django.contrib.postgres.indexes.HashIndex(fields=['sent_by'], name='deals_deal_sent_by_8281f1_hash'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=django.contrib.postgres.indexes.HashIndex(fields=['status'], name='deals_deal_status_28cbc0_hash'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=django.contrib.postgres.indexes.HashIndex(fields=['created_at'], name='deals_deal_created_feb6cc_hash'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['created_at'], name='deals_deal_created_cfe37c_btree'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['status', 'created_at'], name='deals_deal_status_ec8fe0_btree'),
        ),
    ]
