# Generated by Django 3.0.10 on 2020-11-23 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_auto_20201122_1734'),
        ('deals', '0004_deal_sent_by'),
    ]

    operations = [
    ]
