# Generated by Django 3.0.10 on 2020-12-08 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0006_auto_20201127_2148'),
        ('deals', '0006_auto_20201122_2302'),
    ]

    operations = [
    ]
