# Generated by Django 3.0.10 on 2020-12-10 02:26

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0007_merge_20201207_2200'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='deal',
            index=django.contrib.postgres.indexes.HashIndex(fields=['sent_by'], name='deals_deal_sent_by_8281f1_hash'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=django.contrib.postgres.indexes.HashIndex(fields=['status'], name='deals_deal_status_28cbc0_hash'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=django.contrib.postgres.indexes.HashIndex(fields=['status', 'sent_by'], name='deals_deal_status_eeed6a_hash'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['created_at'], name='deals_deal_created_cfe37c_btree'),
        ),
    ]
