# Generated by Django 3.0.10 on 2020-12-10 04:10

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0008_auto_20201210_0226'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='deal',
            name='deals_deal_status_eeed6a_hash',
        ),
        migrations.AddIndex(
            model_name='deal',
            index=django.contrib.postgres.indexes.HashIndex(fields=['created_at'], name='deals_deal_created_feb6cc_hash'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['status', 'created_at'], name='deals_deal_status_ec8fe0_btree'),
        ),
    ]
